version: "3"

services:
  app:
    image: php:7.2-alpine
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: ["bin/console", "server:run", "0.0.0.0"]

  encore:
    image: node:10-alpine
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    working_dir: /app
    command: ["yarn", "dev-server", "--host=0.0.0.0", "--port=8080"]
